# Имя вашего сайта, будет отображаться в шапке
site_name: 'Вики - SP.A'
site_description: 'База знаний сервера SP.A'

# URL, по которому будет доступна ваша вики.
# Замените your-domain.com на ваш реальный домен, когда он появится.
# Окончание /wiki/ здесь КРИТИЧЕСКИ ВАЖНО!
site_url: 'https://zn-worlds.ado-dokidokihimitsukichi-daigakuimo.ru/wiki/'

# Подключение кастомных CSS и JS
extra_css:
  - extra.css
extra_javascript:
  - extra.js

# Указываем папку для кастомных шаблонов
custom_dir: overrides

# Настройки темы
theme:
  name: 'material'
  language: 'ru'
  logo: 'images/logo-white.svg'
  favicon: 'images/logo-white.svg'
  palette:
    # Светлая тема по умолчанию
    - scheme: default
      primary: 'deep purple'
      accent: 'blue'
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему
    # Темная тема для переключения
    - scheme: slate
      primary: 'deep purple'
      accent: 'blue'
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  features:
    - navigation.top
    - navigation.sections

# Навигация по сайту (ваше меню)
nav:
  - '← На главный сайт': '/index.html'
  - '---' # Горизонтальная линия-разделитель
  - 'Главная': 'index.md'
  - 'Первые шаги': 'getting_started.md'
  - 'Правила сервера': 'rules.md'
  - 'Миры и особенности':
    - 'Описание миров': 'worlds.md'
    - 'Ивенты': 'events.md'
  - 'Игровые механики':
    - 'Экономика': 'economy.md'
    - 'Приват территорий': 'privatization.md'
    - 'Кланы': 'clans.md'
    - 'Магазины игроков': 'chestshop.md'
  - 'Сообщество':
    - 'Команда проекта': 'staff.md'
    - 'Голосование за сервер': 'voting.md'
  - 'Ранги и донат': 'ranks.md'
  - 'Справочник команд': 'commands.md'
  - 'Словарь терминов': 'glossary.md'
  - 'FAQ': 'faq.md'
